title: Jardín Digital Andrés
description: Ideas, notas y experimentos.
author: Andrés

collections:
  notes:
    output: true
    permalink: /notes/:path/

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

theme: null

exclude:
  - README.md
